### ISSUE TITLE
 Broken Links

### ISSUE THREAD

**Issue by Us-sync** [hiteshchoudhary/freeApiAppWeb#1]
![image](https://github.com/hiteshchoudhary/freeApiAppWeb/assets/81313264/d311cf5c-345b-4b48-9850-78fbcf609fa7)

**Link 1 - Cooked In Docs
Link 2- Setup Videos**

@hiteshchoudhary

**Comment by anirudhuuu** [comment]
Hi @11WALTER11,

Docs are already available in the FreeApi.app project, setup video will be made available soon & we will update the website.

**Comment by hiteshchoudhary** [comment]
Dropped setup video from 10pm, today.
