### ISSUE TITLE
Bug: ::before eliment in h1 is bloacking the button

### ISSUE THREAD

**Issue by saketverma-03** [hiteshchoudhary/freeApiAppWeb#2]
![image](https://github.com/hiteshchoudhary/freeApiAppWeb/assets/63857530/a6fb6d28-0bcd-4e4d-bdde-cdc8104d8167)

**Solution**
add `z-index:` some -ve value, it wont affect the backdrop shadow

we need to edit property at line 100 in this file https://github.com/hiteshchoudhary/freeApiAppWeb/blob/main/app/page.module.css
 i can fix it you can assign this to me

**Comment by anirudhuuu** [comment]
Hi @saketverma-03, adding `z-index` might not be the right solution for this

**Comment by saketverma-03** [comment]
> Hi @saketverma-03, adding `z-index` might not be the right solution for this

It worked when i added `z-index: -3` using devloper tools in browser.
It is possible solution. 
What can be the downside of this approach ?

**Comment by hiteshchoudhary** [comment]
Let's go for something good and big. Focus on adding value to learners, who will be using this repo as local resources.
